### ISSUE TITLE
Segmentation Fault when loading 'coq/theories/Numbers/Cyclic/Int63/PrimInt63.v'

### ISSUE THREAD

**Issue by laetitia-teo** [sr-lab/coqpyt#35]
Hi,

I've been plagued with segfaults when opening a particular file from the standard library ('coq/theories/Numbers/Cyclic/Int63/PrimInt63.v').

I'm on Ubuntu 20.04.3 LTS.

### Steps to reproduce

Pretty straightforward, the error happens on file open.

```python
# Open Coq file
with CoqFile('/home/<user>/.opam/default/lib/coq/theories/Numbers/Cyclic/Int63/PrimInt63.v') as coq_file:
    pass
```

Looking into more detail, the segfault happens on flushing of the BufferedWriter in the json rpc endpoint, when sending a `'coq\getDocument'` request (`/coqpyt/coqpyt/lsp/json_rpc_endpoint.py`, line 61):

```python
    def send_request(self, message):  # message['method'] == 'coq/getDocument'
        """
        Sends the given message.

        :param dict message: The message to send.
        """
        try:
            json_string = json.dumps(message, cls=MyEncoder)
            jsonrpc_req = self.__add_header(
            with self.write_lock:
                self.stdin.write(jsonrpc_req.encode())
                self.stdin.flush()  # happens here
        except BrokenPipeError as e:
            logging.error(e)
```
I've tried reinstalling coq, using different versions of python, to no avail. Any idea of what might be happening here? This also only show up for this particular file (other coq standard theories are fine).

**Comment by Nfsaavedra** [comment]
Hello @laetitia-teo,

I did some debugging and the segmentation fault apparently comes from [coq-lsp](https://github.com/ejgallego/coq-lsp), so we can't do much about it. Your best option is probably to create an issue in [coq-lsp](https://github.com/ejgallego/coq-lsp) to see if they can fix the bug. 

You can also try to use the last version of coq-lsp in the main branch and check if it fixes the problem.

**Comment by Nfsaavedra** [comment]
> Hi folks, thanks for your patience, this is a
> 
> Duplicate of [ejgallego/coq-serapi#397](https://github.com/ejgallego/coq-serapi/issues/397)
> 
> I've fixed the bug, an updated coq-serapi version should appear soon in Opam.

Thanks @ejgallego!

**Comment by ejgallego** [comment]
Hi folks, fixed versions are being released into opam (cc: https://github.com/ocaml/opam-repository/pull/25552 for 8.19, etc... )

You can close this issue IMHO
